### ISSUE TITLE
Cannot import Fallout New Vegas skeleton

### ISSUE THREAD

**Issue by JettG** [niftools/blender_nif_plugin#350] opened 2020-05-13 08:36 UTC
@niftools/blender-nif-plugin-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
I receive an error when attempting to import any Fallout New Vegas (human) skeleton.nif files. Skeleton is not imported. I suspect there is either an issue with specifically the FNV skeleton, or my import settings (shown below) - I left everything as default except for choosing "Import skeleton only and make it parent of selected meshes." Error also occurs if "everything" option is chosen instead.

Apologies if this has already been reported/documented. I did not see any issues regarding importing skeletons.

### Blender Nif Plugin Version Info
Nif Plugin v2.6.0.dev4

### Blender Version Info
Blender v2.7.9

### Platform information
Microsoft Windows 10 Home 10.0.17763

## Context
This error first occurred when I had finished with a mesh and was going to import the fnv skeleton to parent my mesh to it. I tried with vanilla FNV skeleton.nif, and a couple others from modders resources. I also tried importing the skeleton from an empty blender file. I haven't had any issues importing non-armature mesh.nif files (including those with a skeleton already included).
## Steps to Reproduce
1. Open fresh file in Blender (or existing file with FNV mesh objects within).
2. Import human skeleton.nif for Fallout New Vegas using the settings shown in screenshot below.
3. Receive error message.
 #. 

## Expected Result
Successfully import skeleton.nif from FNV game files into blender file.

## Actual Result
Error message as seen below - skeleton is not imported.
## Possible Fix
Perhaps there is an issue with my import settings?
## Screenshot
![blender error](https://user-images.githubusercontent.com/52123861/81787440-aa4f9880-94c6-11ea-9f94-f476a2f330f9.png)

![import settings](https://user-images.githubusercontent.com/52123861/81789472-a83b0900-94c9-11ea-8061-51048f1f1b9e.png)

![green stuff](https://user-images.githubusercontent.com/52123861/81790254-c3f2df00-94ca-11ea-8ae8-2a4b90e2eab2.png)

### Info Bar Output
Not sure if noteworthy but the log/console/whatever reports "reading file -> importing data -> finished" and *then* reports the error. There is a screenshot showing this.
### Blend File
I was able to reproduce this error with a fresh (empty default) blender file.

### Nif File
nif file is in the .zip archive. This should be the vanilla FNV skeleton.
[skeleton.zip](https://github.com/niftools/blender_nif_plugin/files/4623776/skeleton.zip)

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

## Similar Known Issues
There is a recent issue where someone had trouble *exporting* a skeleton, so perhaps it is related.

**Comment by neomonkeus** [comment] 2020-05-13 10:53
@JettG I have readded the parts of the template which were removed, as per the issue template. 
Can you provide the nif in question.

**Comment by HENDRIX-ZT2** [comment] 2020-05-13 11:27
See my comment in commit - this made sure it worked for the previous nif.xml version:
https://github.com/niftools/pyffi/commit/7b2609575bc4d40592dcee2cbdb03d94db071c15

This error is due to the bump of the nif.xml version after release of pyffi2.2.4.dev3, which has restored that subconstraint:
dev3 nif xml: https://github.com/niftools/nifxml/blob/959cb9c3dd59a319e60e819fc8a1402f821f3684/nif.xml#L2019
dev4 nif.xml: https://github.com/niftools/nifxml/blob/f265c56482c728c6877e45d5b5993d3bff83670a/nif.xml#L2180

**Comment by neomonkeus** [comment] 2020-05-13 12:23
What are we thinking, based on going back to dev3.

**Comment by HENDRIX-ZT2** [comment] 2020-05-13 12:35
I think dev3 is the only viable option for now, as even the slightest update of the nif xml wreaks havoc. Anything else just slows down the plugin development. We can look at upgrading pyffi and the xml once the plugin is relatively stable.

**Comment by neomonkeus** [comment] 2020-05-13 12:52
We'll use this ticket to revert back to dev3 then. 👍

**Comment by JettG** [comment] 2020-05-13 18:13
I added the nif file in a zipped archive. Sorry I didn't do it before github would not accept .nif files and it didn't occur to me to zip it up yesterday evening.

**Comment by neomonkeus** [comment] 2020-05-13 18:19
Thanks. Yes even though we think we know what the underlying issue is it is good to have it to reproduce and test.

**Comment by JettG** [comment] 2020-05-16 05:03
Is there somewhere I can ask general questions about using this tool? The discord link is broken for me and I don't want to spam the issues section with beginner questions. 

I have some modeling and texturing experience but working with nifs is mostly new to me.

**Comment by neomonkeus** [comment] 2020-05-16 10:09
https://discord.gg/JjHKVNc

**Comment by HENDRIX-ZT2** [comment] 2020-05-26 21:05
With #362 merged, this should be fixed since we're back to pyffi dev3

**Comment by neomonkeus** [comment] 2020-05-26 21:29
Tested with pyffi dev3

**Closed** 2020-05-27 07:47 UTC
Labels: Bug
