### ISSUE TITLE
Addon enabled in Blender 2.82.7, Option to Import and Export .NIF Files not appearing under File

### ISSUE THREAD

**Issue by nolanbatten** [niftools/blender_nif_plugin#324] opened 2020-03-23 02:59 UTC
![AddonEnabled](https://user-images.githubusercontent.com/43045467/77276295-46f47780-6c88-11ea-9978-c8030358e114.PNG)
![No_NIF_Import Option](https://user-images.githubusercontent.com/43045467/77276311-4fe54900-6c88-11ea-9e0d-db00b1d8f72d.PNG)

**Comment by TagnumElite** [comment] 2020-03-23 05:56
Blender 2.8+ isn't supported right now. We are currently trying to get all issues resolved with 2.79.

**Comment by neomonkeus** [comment] 2020-03-23 12:52
Closing as duplicates #279, didn't read template to see if issue was already reported and also remove template.
Also the irony of the issue is 279....

**Closed by neomonkeus** 2020-03-23 12:52 UTC
Labels: Duplicate, Invalid
