### ISSUE TITLE
Export only selected Armature

### ISSUE THREAD

**Issue by Ghostwalker71** [niftools/blender_nif_plugin#145] opened 2014-01-17 16:26 UTC
Currently if there are two or more armatures in the scene the script throws an error about multiple bone with the same name, I think this is due to how blender now stores bones inside the armature. we need to add a check so that only the items that are selected and those linked to them are processed for export. Selected export has been requested a few times anyway.

**Comment by HENDRIX-ZT2** [comment] 2019-09-18 08:47
Fixed by PR #289. You can now have multiple armatures in a scene and export only one, the selected one and its children. That works.

If you select more than one armature for export, you still get the old error. We would probably need one dict per armature to overcome it. The issue is here:
``` python
for block in self.nif_export.block_to_obj:
    if isinstance(block, NifFormat.NiNode):
        if block.name.decode() == self.nif_export.objecthelper.get_full_name(b_obj_armature.data.bones[bone]):
            if not bone_block:
                bone_block = block
            else:
                raise nif_utils.NifError("Multiple bones with name '%s': "
             "probably you have multiple armatures. "
             "Please parent all meshes to a single armature and try again"
             % bone)
```

https://github.com/niftools/blender_nif_plugin/blob/develop/io_scene_nif/modules/object/object_export.py#L1175

But tbh. I would just forbid this. Check if more than one armature is in exportable_objects and raise a user-friendly warning like "You have selected more than one armature, select only one".

**Closed** 2020-05-27 15:01 UTC
Labels: Bug, Improvement, New Feature
